version: "3"
services:
  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
  dice-service:
    build: ./dice-service
    ports:
      - "5001"
  datadog:
    image: datadog/agent:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/proc/:/host/proc/:ro"
      - "/sys/fs/cgroup/:/host/sys/fs/cgroup:ro"
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED: 'true'
      - DD_LOGS_ENABLED: 'true'
      - DD_PROCESS_AGENT_ENABLED: 'true'
